name: Dynamic CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  dynamic-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          if [ ! -d ".github/tests_pipelines" ]; then
            echo "Error: Directory .github/tests_pipelines does not exist"
            exit 1
          fi
          for file in $(find .github/tests_pipelines -name '*.yml'); do
            echo "Processing $file"
          
            # Extract paths from YAML
            BASIC_PATH=$(yq '.variables.BASIC_PATH' "$file")
            REQUIREMENTS_PATH=$(yq '.variables.REQUIREMENTS_PATH' "$file" | sed "s|\${BASIC_PATH}|$BASIC_PATH|g")
            TEST_PATH=$(yq '.variables.TEST_PATH' "$file" | sed "s|\${BASIC_PATH}|$BASIC_PATH|g")
          
            echo "Checking requirements file at $REQUIREMENTS_PATH"
            cat "$REQUIREMENTS_PATH"
          
            echo "Installing dependencies from $REQUIREMENTS_PATH"
            pip install --upgrade pip
            pip install -r "$REQUIREMENTS_PATH"
          
            echo "Installing Playwright browsers"
            playwright install
          
            echo "Running tests from $TEST_PATH"
            xvfb-run pytest "$TEST_PATH"
          done

      - name: Run tests
        run: |
          for file in $(find .github/tests_pipelines -name '*.yml'); do
            echo "Processing $file"
            BASIC_PATH=$(yq '.variables.BASIC_PATH' "$file")
            TEST_PATH=$(yq '.variables.TEST_PATH' "$file" | sed "s|\${BASIC_PATH}|$BASIC_PATH|g")
            echo "Running tests from $TEST_PATH"
            
            # Run tests with xvfb-run
            xvfb-run pytest "$TEST_PATH"
          done
