name: Dynamic CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  dynamic-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install yq for YAML parsing
      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      # Parse all YAML files in tests/pipelines
      - name: Load YAML files and run tests
        run: |
          for file in $(find tests_pipelines -name '*.yml'); do
            echo "Processing $file"
            TEST_PATH=$(yq '.variables.TEST_PATH' "$file")
            REQUIREMENTS_PATH=$(yq '.variables.REQUIREMENTS_PATH' "$file")
            echo "Found TEST_PATH=$TEST_PATH and REQUIREMENTS_PATH=$REQUIREMENTS_PATH"

            # Install dependencies
            pip install --upgrade pip
            pip install -r "$REQUIREMENTS_PATH"

            # Run tests
            pytest "$TEST_PATH"
          done
