name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-basic-search:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r tests/basic_search/requirements.txt

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: playwright install

      # Run tests with xvfb
      - name: Run tests with xvfb
        run: xvfb-run pytest tests/basic_search/test_basic_search.py
