name: Dynamic CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  dynamic-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Проверка содержимого
      - name: List files in .github directory
        run: ls -R .github

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install yq for YAML parsing
      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      # Install Playwright and browsers
      - name: Install Playwright and browsers
        run: playwright install

      # Parse all YAML files in .github/tests_pipelines and run tests
      - name: Load YAML files and run tests
        run: |
          if [ ! -d ".github/tests_pipelines" ]; then
            echo "Error: Directory .github/tests_pipelines does not exist"
            exit 1
          fi
          for file in $(find .github/tests_pipelines -name '*.yml'); do
            echo "Processing $file"
            BASIC_PATH=$(yq '.variables.BASIC_PATH' "$file")
            TEST_PATH=$(yq '.variables.TEST_PATH' "$file" | sed "s|\${BASIC_PATH}|$BASIC_PATH|g")
            REQUIREMENTS_PATH=$(yq '.variables.REQUIREMENTS_PATH' "$file" | sed "s|\${BASIC_PATH}|$BASIC_PATH|g")
            echo "Found TEST_PATH=$TEST_PATH and REQUIREMENTS_PATH=$REQUIREMENTS_PATH"

            # Install dependencies
            pip install --upgrade pip
            pip install -r "$REQUIREMENTS_PATH"

            # Run tests
            pytest "$TEST_PATH"
          done
